Filter
FatimaAbdimalik/Feedback-Compass pull request #23
Opened 2020-11-01 07:36 UTC by FatimaAbdimalik

Thank you for contributing! To help the review process, please provide the following:

### Proposal
Provide a short description of the change you are proposing and the reasons for it.

### Related
Provide links to any associated pull requests or issues. You can use `#123` to link to a PR or issue in this repository, or `user/repo#123` to link to other repositories.

### Checklist

- [ ] I have read the [code of conduct] and [contributing guide]
- [ ] I have made this pull request to the `master` branch
- [ ] I have run all of the automated validation using `npm run ship`
- [ ] I have added myself to the `"contributors"` list in the `package.json` (or do not want to)

[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

2020-11-01 19:52 UTC, Hedyeh65 requested changes
good job Fatima!

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/Filter.js
> +      {/* <SubmissionCard id={id} /> */}
please remove this lines

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/LessonsDropDown.js
>        console.log(response);
This console.log should be removed

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/MentorViewSubmission.js
> +    console.log(value);
please remove this console.log

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/MentorViewSubmission.js
> +      console.log(cardData);
please remove these 2 console.logs

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/MentorViewSubmission.js
> +                    {" "}
please remove the brackets

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/ModuleDropDown.js
> +  console.log(id);
pleaswe remove this log

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/SubmissionCard.js
> +      console.log(cardData);
remove these 2 console.logs

2020-11-01 19:52 UTC, Hedyeh65 commented on client/src/components/SubmissionCard.js
> +                  {" "}
remove these brackets

2020-11-02 08:39 UTC, SULAIMAN-100 commented on client/src/components/Filter.js
> +export default Filter;
could you give the file more specified name like filter cards or filter card title.

2020-11-02 13:03 UTC, SULAIMAN-100 approved these changes

2020-11-02 14:53 UTC, Hedyeh65 approved these changes

2020-11-02 14:53 UTC, merged