Student response
FatimaAbdimalik/Feedback-Compass pull request #24
Opened 2020-11-01 19:15 UTC by SULAIMAN-100

Thank you for contributing! To help the review process, please provide the following:

### Proposal
Provide a short description of the change you are proposing and the reasons for it.

### Related
Provide links to any associated pull requests or issues. You can use `#123` to link to a PR or issue in this repository, or `user/repo#123` to link to other repositories.

### Checklist

- [ ] I have read the [code of conduct] and [contributing guide]
- [ ] I have made this pull request to the `master` branch
- [ ] I have run all of the automated validation using `npm run ship`
- [ ] I have added myself to the `"contributors"` list in the `package.json` (or do not want to)

[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

2020-11-01 22:51 UTC, Hedyeh65 requested changes

2020-11-01 22:51 UTC, Hedyeh65 commented on client/src/components/MentorViewSubmission.js
> +        console.log(response.data.map((id) => id.id));
please remove the console.log

2020-11-01 22:51 UTC, Hedyeh65 commented on client/src/components/ModuleDropDown.js
> +  console.log(id);
remove this console.log please

2020-11-01 22:51 UTC, Hedyeh65 commented on client/src/components/SubmissionCard.js
> +                {" "}
remove this bracket please

2020-11-01 22:51 UTC, Hedyeh65 commented on server/db.js
> +    password: "12133405",
remove your password please

2020-11-02 08:03 UTC, FatimaAbdimalik requested changes

2020-11-02 08:32 UTC, FatimaAbdimalik approved these changes

2020-11-02 14:53 UTC, merged