More features
FatimaAbdimalik/Feedback-Compass pull request #27
Opened 2020-11-03 15:56 UTC by SULAIMAN-100

Thank you for contributing! To help the review process, please provide the following:

### Proposal
Provide a short description of the change you are proposing and the reasons for it.

### Related
Provide links to any associated pull requests or issues. You can use `#123` to link to a PR or issue in this repository, or `user/repo#123` to link to other repositories.

### Checklist

- [ ] I have read the [code of conduct] and [contributing guide]
- [ ] I have made this pull request to the `master` branch
- [ ] I have run all of the automated validation using `npm run ship`
- [ ] I have added myself to the `"contributors"` list in the `package.json` (or do not want to)

[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

2020-11-04 09:53 UTC, FatimaAbdimalik requested changes
push the changes in courseProgressList before merging Leida's branch please.

2020-11-04 11:00 UTC, Hedyeh65 requested changes

2020-11-04 11:00 UTC, Hedyeh65 commented on compass copy.sql
> -drop table if exists feedbacktable
please sort this file before you push

2020-11-07 18:40 UTC, FatimaAbdimalik approved these changes

2020-11-07 18:49 UTC, Leidagandy approved these changes

2020-11-07 19:05 UTC, Hedyeh65 approved these changes

2020-11-07 19:06 UTC, merged